daysUntilStale: 15
daysUntilClose: 5
staleLabel: "r: stale"
exemptLabels:
  - "pinned"
  - "t: bug"
  - "t: security"
  - "t: new platform"

markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
closeComment: >
  This issue has been automatically closed because it had no activity since the
  last call. If the issue still applies to the most recent supported
  version, please open a new issue referencing this original issue.
