[versions]

# plugins
indra = "4.0.0"
shadow = "9.3.1"
juppiter = "0.5.0-beta.2"
spotless = "8.9.0"
nexusPublish = "2.0.0"
checkstyleTools = "13.10.0"

# google libs
gson = "2.14.0"
guava = "33.6.0-jre"

# testing
junit = "6.0.3"
mockito = "5.21.0"
testcontainers = "2.0.5"

# compile time processing
lombok = "1.18.46"
javapoet = "1.13.0"

# console
jline = "4.4.0"
cloud = "2.0.0-cn1"
cloudApi = "2.0.0"
stringSimilarity = "2.0.0"
cloudConfirmation = "1.0.0-rc.1"

# databases
h2 = "1.4.197" # do not update, leads to database incompatibility
xodus = "2.0.1"
mongodb = "5.6.5"
hikariCp = "7.0.2"
mysqlConnector = "9.7.0"

# general
oshi = "7.4.4"
gulf = "0.0.1"
vavr = "1.0.1"
sshj = "0.40.0"
aerogel = "3.1.0"
awsSdk = "2.41.11"
unirest = "4.7.4"
caffeine = "3.2.4"
reflexion = "2.0.0"
geantyref = "2.0.1"
dockerJava = "3.7.1"
nightConfig = "3.8.4"
annotations = "26.1.0"
influxClient = "7.4.0"
netty = "2025.11.08-3a259e91"

# logging
slf4j = "2.0.18"
logback = "1.5.32"

# platform api versions
sponge = "9.0.0"
velocity = "3.5.1"
waterdogpe = "1.2.4"
nukkitX = "1.0-SNAPSHOT"
minestom = "2026.08.07-26.2"
minestomExtensions = "1.2.0"
spigot = "1.8.8-R0.1-SNAPSHOT"
bungeecord = "26.1-R0.1-SNAPSHOT"
limboloohp = "0.7.9-ALPHA"
folia = "1.21.11-R0.1-SNAPSHOT"

# platform extensions
adventure = "4.26.1"
modlauncher = "8.1.3"
npcLib = "3.0.0-beta.17"
packetEvents = "2.13.0"
placeholderApi = "2.12.3"
adventure-serializer-bungee = "4.4.1"
luckPermsApi = "5.5"
fabricLoader = "0.19.3"


[libraries]

# compile time processing
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
javapoet = { group = "com.squareup", name = "javapoet", version.ref = "javapoet" }

# google libs
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

# console
jansi = { group = "org.jline", name = "jansi-core", version.ref = "jline" }
jlineReader = { group = "org.jline", name = "jline-reader", version.ref = "jline" }
jlineTerminal = { group = "org.jline", name = "jline-terminal-ffm", version.ref = "jline" }
stringSimilarity = { group = "info.debatty", name = "java-string-similarity", version.ref = "stringSimilarity" }

# night config
nightConfigToml = { group = "com.electronwill.night-config", name = "toml", version.ref = "nightConfig" }
nightConfigYaml = { group = "com.electronwill.night-config", name = "yaml", version.ref = "nightConfig" }
nightConfigJson = { group = "com.electronwill.night-config", name = "json", version.ref = "nightConfig" }

# cloud commands
cloudCore = { group = "com.github.CloudNetService.cloud-command-framework", name = "cloud-core", version.ref = "cloud" }
cloudAnnotations = { group = "com.github.CloudNetService.cloud-command-framework", name = "cloud-annotations", version.ref = "cloud" }
cloudConfirmationProcessor = { group = "org.incendo", name = "cloud-processors-confirmation", version.ref = "cloudConfirmation" }

# cloud api to expose in node api
cloudCoreApi = { group = "org.incendo", name = "cloud-core", version.ref = "cloudApi" }
cloudAnnotationsApi = { group = "org.incendo", name = "cloud-annotations", version.ref = "cloudApi" }

# junit
junitApi = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junitParams = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }
junitEngine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
junitLauncher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit" }

# general testing
mockito = { group = "org.mockito", name = "mockito-junit-jupiter", version.ref = "mockito" }

# testcontainers
testContainers = { group = "org.testcontainers", name = "testcontainers", version.ref = "testcontainers" }
testContainersJunit = { group = "org.testcontainers", name = "testcontainers-junit-jupiter", version.ref = "testcontainers" }

# unirest
unirest = { group = "com.konghq", name = "unirest-java-core", version.ref = "unirest" }
unirestGson = { group = "com.konghq", name = "unirest-modules-gson", version.ref = "unirest" }

# docker-java
dockerJavaApi = { group = "com.github.docker-java", name = "docker-java-core", version.ref = "dockerJava" }
dockerJavaHttpclient5 = { group = "com.github.docker-java", name = "docker-java-transport-httpclient5", version.ref = "dockerJava" }

# netty
nettyHandler = { group = "io.netty", name = "netty5-handler", version.ref = "netty" }
nettyNativeEpoll = { group = "io.netty", name = "netty5-transport-native-epoll", version.ref = "netty" }
nettyNativeKqueue = { group = "io.netty", name = "netty5-transport-native-kqueue", version.ref = "netty" }

# logging
slf4jApi = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
logbackCore = { group = "ch.qos.logback", name = "logback-core", version.ref = "logback" }
logbackClassic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }

# general
vavr = { group = "io.vavr", name = "vavr", version.ref = "vavr" }
sshj = { group = "com.hierynomus", name = "sshj", version.ref = "sshj" }
gulf = { group = "dev.derklaro.gulf", name = "gulf", version.ref = "gulf" }
awsSdk = { group = "software.amazon.awssdk", name = "s3", version.ref = "awsSdk" }
oshi = { group = "com.github.oshi", name = "oshi-core-ffm", version.ref = "oshi" }
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
geantyref = { group = "io.leangen.geantyref", name = "geantyref", version.ref = "geantyref" }
caffeine = { group = "com.github.ben-manes.caffeine", name = "caffeine", version.ref = "caffeine" }
reflexion = { group = "dev.derklaro.reflexion", name = "reflexion-core", version.ref = "reflexion" }
influxClient = { group = "com.influxdb", name = "influxdb-client-java", version.ref = "influxClient" }

# aerogel
aerogel = { group = "dev.derklaro.aerogel", name = "aerogel", version.ref = "aerogel" }
aerogelAuto = { group = "dev.derklaro.aerogel", name = "aerogel-auto", version.ref = "aerogel" }
aerogelScopedValues = { group = "dev.derklaro.aerogel", name = "aerogel-scoped-value-context-scope", version.ref = "aerogel" }

# databases
h2 = { group = "com.h2database", name = "h2", version.ref = "h2" }
hikariCp = { group = "com.zaxxer", name = "HikariCP", version.ref = "hikariCp" }
mongodb = { group = "org.mongodb", name = "mongodb-driver-sync", version.ref = "mongodb" }
xodus = { group = "org.jetbrains.xodus", name = "xodus-environment", version.ref = "xodus" }
mysqlConnector = { group = "com.mysql", name = "mysql-connector-j", version.ref = "mysqlConnector" }

# platform api
nukkitX = { group = "cn.nukkit", name = "nukkit", version.ref = "nukkitX" }
spigot = { group = "org.spigotmc", name = "spigot-api", version.ref = "spigot" }
sponge = { group = "org.spongepowered", name = "spongeapi", version.ref = "sponge" }
bungeecord = { group = "net.md-5", name = "bungeecord-api", version.ref = "bungeecord" }
minestom = { group = "net.minestom", name = "minestom", version.ref = "minestom" }
minestomExtensions = { group = "dev.hollowcube", name = "minestom-ce-extensions", version.ref = "minestomExtensions" }
velocity = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }
waterdogpe = { group = "dev.waterdog.waterdogpe", name = "waterdog", version.ref = "waterdogpe" }
limboloohp = { group = "com.loohp", name = "Limbo", version.ref = "limboloohp" }
folia = { group = "dev.folia", name = "folia-api", version.ref = "folia" }

# adventure
adventureApi = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventureSerializerGson = { group = "net.kyori", name = "adventure-text-serializer-gson", version.ref = "adventure" }
adventureSerializerLegacy = { group = "net.kyori", name = "adventure-text-serializer-legacy", version.ref = "adventure" }
adventureSerializerBungee = { group = "net.kyori", name = "adventure-text-serializer-bungeecord", version.ref = "adventure-serializer-bungee" }

# platform extensions
modLauncher = { group = "cpw.mods", name = "modlauncher", version.ref = "modlauncher" }
bungeecordChat = { group = "net.md-5", name = "bungeecord-chat", version.ref = "bungeecord" }
placeholderApi = { group = "me.clip", name = "placeholderapi", version.ref = "placeholderApi" }

npcLib = { group = "io.github.juliarn", name = "npc-lib-bukkit", version.ref = "npcLib" }
packetEvents = { group = "com.github.retrooper", name = "packetevents-spigot", version.ref = "packetEvents" }
npcLibLabymod = { group = "io.github.juliarn", name = "npc-lib-labymod", version.ref = "npcLib" }
luckPermsApi = { group = "net.luckperms", name = "api", version.ref = "luckPermsApi" }
fabricLoader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabricLoader" }

# dummy versions, just here for renovate to detect that there is something to update
checkstyleTools = { group = "com.puppycrawl.tools", name = "checkstyle", version.ref = "checkstyleTools" }


[bundles]

aerogel = ["aerogel", "aerogelScopedValues", "aerogelAuto"]
aerogelApi = ["aerogel", "aerogelAuto"]
npcLib = ["npcLib", "npcLibLabymod"]
unirest = ["unirest", "unirestGson"]
mysql = ["mysqlConnector", "hikariCp"]
jline = ["jlineReader", "jlineTerminal"]
cloud = ["cloudCore", "cloudAnnotations", "cloudConfirmationProcessor"]
cloudApi = ["cloudCoreApi", "cloudAnnotationsApi", "cloudConfirmationProcessor"]
netty = ["nettyHandler"]
junit = ["junitApi", "junitParams", "junitEngine"]
dockerJava = ["dockerJavaApi", "dockerJavaHttpclient5"]
testContainers = ["testContainers", "testContainersJunit"]
nightConfig = ["nightConfigToml", "nightConfigYaml", "nightConfigJson"]
adventure = ["adventureApi", "adventureSerializerGson", "adventureSerializerLegacy"]

proxyPlatform = ["bungeecord", "velocity", "waterdogpe"]
serverPlatform = ["spigot", "sponge", "nukkitX", "minestom", "minestomExtensions", "limboloohp"]


[plugins]

indra = { id = "net.kyori.indra.git", version.ref = "indra" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
juppiter = { id = "eu.cloudnetservice.juppiter", version.ref = "juppiter" }
nexusPublish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexusPublish" }
