name: Bug report
description: Report exceptions, crashes or any bug you encounter while using CloudNet.
labels: [ "s: needs triage", "t: bug" ]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug of CloudNet. Please be as detailed as possible in order for us
        to quickly review and resolve the issues you have. Please check if a similar report
        was already opened by searching through the opened and closed issues. If there is an existing
        issue please comment there if you have anything to add. If you are unsure if you actually
        encountered a bug, join and ask on our discord server: https://discord.cloudnetservice.eu.

  - type: textarea
    attributes:
      label: Stacktrace
      description: |
        Attach your stack trace here (if any). Ensure that the stack trace is related to CloudNet
        and do not cut off any parts of it. Please put your stacktrace either directly into the text
        field or use https://gist.new for stack traces. Some providers are deleting pastes after some
        time, so please stick to raw logs or gists. DO NOT use attachments for posting logs or exceptions.
      value: |
        ```
        Paste your paste link or the raw stack trace here. DO NOT REMOVE THE BACKTICKS!
        ```
    validations:
      required: false

  - type: textarea
    attributes:
      label: Actions to reproduce
      description: |
        Try to explain to us what you did before getting the issue. This makes it much easier for us to
        reproduce and resolve your issue. You can attach screenshots or videos if these are helping us
        to understand what happened.
    validations:
      required: true

  - type: textarea
    attributes:
      label: CloudNet version
      description: |
        Run `me` in the node console and paste the full, unmodified output here. DO NOT use an attachments
        here, just paste the output.
        <details>
        <summary>Example</summary>
        ```
        root@4.0.0-RC2-SNAPSHOT-e7970652 => me
        [28.08 19:27:50.428] INFO:
        [28.08 19:27:50.429] INFO: CloudNet Blizzard 4.0.0-RC2-SNAPSHOT e7970652
        [28.08 19:27:50.430] INFO: Discord: <https://discord.cloudnetservice.eu/>
        [28.08 19:27:50.430] INFO:
        [28.08 19:27:50.430] INFO: ClusterId: a4d58965-****-41a3-****-e1f6d03a16ce
        [28.08 19:27:50.431] INFO: NodeId: Node-1
        [28.08 19:27:50.431] INFO: Head-NodeId: Node-1
        [28.08 19:27:50.431] INFO: CPU usage: (P/S) 4/3/100%
        [28.08 19:27:50.432] INFO: Node services memory allocation (U/R/M): 0/0/6094 MB
        [28.08 19:27:50.432] INFO: Threads: 32
        [28.08 19:27:50.432] INFO: Heap usage: 70/256MB
        [28.08 19:27:50.433] INFO: JVM: Eclipse Adoptium 17 (OpenJDK 64-Bit Server VM 17.0.4+8)
        [28.08 19:27:50.433] INFO: Update Repo: CloudNetService/launchermeta, Update Branch: release
        [28.08 19:27:50.433] INFO:
        ```
        </details>
    validations:
      required: true

  - type: textarea
    attributes:
      label: Other
      description: Add more context, screenshots or anything else you want to tell us regarding your request
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Issue uniqueness
      description: Please check that there are no similar issues before submitting your request
      options:
        - label: Yes, this issue is unique. There are no similar issues.
          required: true
