blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.cloudnetservice.eu
    about: |
      If you need general support on CloudNet, you should use our Discord server. We and the community can help you
      help you there faster and more targeted.
