/*
 * Copyright 2019-2024 CloudNetService team & contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package eu.cloudnetservice.node.impl.network.listener;

import eu.cloudnetservice.driver.ComponentInfo;
import eu.cloudnetservice.driver.channel.ChannelMessage;
import eu.cloudnetservice.driver.event.EventManager;
import eu.cloudnetservice.driver.event.events.channel.ChannelMessageReceiveEvent;
import eu.cloudnetservice.driver.network.NetworkChannel;
import eu.cloudnetservice.driver.network.buffer.DataBuf;
import eu.cloudnetservice.driver.network.protocol.Packet;
import eu.cloudnetservice.driver.network.protocol.PacketListener;
import eu.cloudnetservice.node.impl.provider.NodeCloudMessenger;
import jakarta.inject.Inject;
import jakarta.inject.Singleton;
import java.util.ArrayList;
import java.util.Objects;
import lombok.NonNull;
import org.jetbrains.annotations.Nullable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@Singleton
public final class ChannelMessagePacketListener implements PacketListener {

  private static final Logger LOGGER = LoggerFactory.getLogger(ChannelMessagePacketListener.class);

  private final NodeCloudMessenger messenger;
  private final EventManager eventManager;
  private final ComponentInfo componentInfo;

  @Inject
  public ChannelMessagePacketListener(
    @NonNull NodeCloudMessenger messenger,
    @NonNull EventManager eventManager,
    @NonNull ComponentInfo componentInfo
  ) {
    this.messenger = messenger;
    this.eventManager = eventManager;
    this.componentInfo = componentInfo;
  }

  @Override
  public void handle(@NonNull NetworkChannel channel, @NonNull Packet packet) {
    // see content and order in ChannelMessagePacket
    var isQuery = packet.uniqueId() != null;
    var packetContent = packet.content();
    var comesFromWrapper = packetContent.readBoolean();
    var channelMessage = packetContent.readObject(ChannelMessage.class);

    var handleLocally = channelMessage.targets().stream().anyMatch(target -> switch (target.type()) {
      case ALL -> true;
      case NODE -> target.name() == null || target.name().equals(this.componentInfo.componentName());
      default -> false;
    });
    if (handleLocally) {
      // message should be handled locally with 2 possible outcomes:
      //  1. a response future gets provided to the handler, we then need to wait until the handler finishes
      //     whatever is required to provide a response and resume handling (redirecting) the message after
      //  2. no response future gets provided, this happens when:
      //      * no listener is registered locally for the message
      //      * a listener is registered but has no response for the query
      //      * the channel message is not a query
      //     in these cases we just resume the message handling instantly
      var messageContent = channelMessage.content();
      messageContent.startTransaction(); // to reset after listeners were called

      var event = this.eventManager.callEvent(new ChannelMessageReceiveEvent(channelMessage, channel, isQuery));
      var responseTask = event.queryResponse();
      if (responseTask != null) {
        responseTask
          .whenComplete((localResponse, _) -> {
            messageContent.redoTransaction(); // redo after processing finished
            this.resumeHandling(packet, channel, channelMessage, localResponse, comesFromWrapper);
          })
          .exceptionally((thrown) -> {
            LOGGER.warn("Exception during async channel message processing of {}", channelMessage, thrown);
            return null;
          });
        return;
      } else {
        messageContent.redoTransaction();
      }
    }

    this.resumeHandling(packet, channel, channelMessage, null, comesFromWrapper);
  }

  /**
   * Resumes the processing of a channel message, redirecting the message to other targets in the cluster and sending
   * back a response in case the original request was a query.
   *
   * @param packet           the packet that contained the initially handled channel message.
   * @param channel          the channel on which the initially handled channel message was received.
   * @param message          the original channel message that was received.
   * @param localResponse    the query response generated by listeners on the current node.
   * @param comesFromWrapper if the handled channel message was sent by a wrapper.
   * @throws NullPointerException if the given packet, channel or initial channel message is null.
   */
  private void resumeHandling(
    @NonNull Packet packet,
    @NonNull NetworkChannel channel,
    @NonNull ChannelMessage message,
    @Nullable ChannelMessage localResponse,
    boolean comesFromWrapper
  ) {
    var isQuery = packet.uniqueId() != null;
    if (isQuery) {
      this.messenger.sendChannelMessageQueryAsync(message, comesFromWrapper)
        .whenComplete((responses, _) -> {
          responses = Objects.requireNonNullElseGet(responses, ArrayList::new);
          if (localResponse != null) {
            responses.add(localResponse);
          }

          var responseBuffer = DataBuf.empty().writeObject(responses);
          var responsePacket = packet.constructResponse(responseBuffer);
          channel.sendPacket(responsePacket);
        })
        .exceptionally(thrown -> {
          LOGGER.debug("Exception while forwarding channel message {} into the cluster", message, thrown);
          return null;
        });
    } else {
      this.messenger.sendChannelMessage(message, comesFromWrapper);
    }
  }
}
