name: "Build"

on:
  push:
    tags: [ "4.*" ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    environment: release
    runs-on: ubuntu-latest
    name: Publish to maven central

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          check-latest: true
          cache: 'gradle'

      - name: Publish release to Sonatype
        run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
        env:
          sonatypeUsername: "${{ secrets.SONATYPE_USER }}"
          sonatypePassword: "${{ secrets.SONATYPE_TOKEN }}"
          signingSecretKey: "${{ secrets.SIGNING_KEY }}"
          signingSecretKeyPassword: "${{ secrets.SIGNING_KEY_PASSWORD }}"
