name: Build and deploy Javadocs

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build javadocs
        run: ./gradlew javadoc

      - name: Deploy javadocs to its assigned branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: javadocs
          FOLDER: build/javadoc
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLEAR_GLOBS_FILE: ".github/javadoc-publish-clear"
